FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY config/requirements.txt config/
RUN pip install --no-cache-dir -r config/requirements.txt

COPY manage.py .

COPY config config
RUN chmod +x config/entrypoint.sh

COPY apps apps
