# Generated by Django 4.2.5 on 2023-09-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=40)),
                ("subnet_mask", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in queue", "In Queue"),
                            ("in progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="in queue",
                        max_length=20,
                    ),
                ),
                ("ip_version", models.IntegerField(choices=[(4, "Ipv4"), (6, "Ipv6")])),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subnet_ip", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=20,
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pinger.network"
                    ),
                ),
            ],
        ),
    ]
